# SPDX-License-Identifier: GPL-2.0-only
[package]
name             = "scrooge-manager-core"
description      = "Core manager logic for ScroogeDLP (policy engine, correlator, store)."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
authors.workspace      = true
repository.workspace   = true
homepage.workspace     = true

[lints]
workspace = true
