#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only
# ScroogeDLP - agent installer (macOS, curl-flow, NO code signing).
# Generated server-side by GET /api/v1/install-macos.sh — do NOT edit on
# disk; the manager re-renders this every request.
#
# macOS quarantine xattr nie jest ustawiany przez curl/wget, wiec Gatekeeper
# nie blokuje binarki. launchctl bootstrap odpala ja jako system daemon.

set -euo pipefail

# ─── Wartości wstrzyknięte przez managera ──────────────────────────────────
MANAGER_ENDPOINT='{{MANAGER_ENDPOINT}}'
INSTALL_BASE_URL='{{INSTALL_BASE_URL}}'
ENROLLMENT_TOKEN='{{ENROLLMENT_TOKEN}}'
RELEASE_TAG='{{RELEASE_TAG}}'
PACKAGE_VERSION='{{PACKAGE_VERSION}}'
RELEASES_BASE='{{RELEASES_BASE}}'

# ─── Inline CA PEM ─────────────────────────────────────────────────────────
CA_PEM=$(cat <<'__SCROOGE_CA_PEM_EOF__'
{{CA_PEM}}
__SCROOGE_CA_PEM_EOF__
)

# ─── Stałe ścieżki macOS ───────────────────────────────────────────────────
PREFIX="/usr/local"
BIN_DIR="${PREFIX}/bin"
ETC_DIR="${PREFIX}/etc/scrooge"
DATA_DIR="/var/lib/scrooge"
LOG_DIR="/var/log"
PLIST_PATH="/Library/LaunchDaemons/com.sqtx.scrooge-agent.plist"
SERVICE_LABEL="com.sqtx.scrooge-agent"

log() { printf '\033[1;36m▸\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31m✗\033[0m %s\n' "$*" >&2; exit 1; }

# ─── Sanity ────────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || fail "ScroogeDLP installer must run as root (try: sudo bash)"

if [[ "$(uname -s)" != "Darwin" ]]; then
  fail "this installer is macOS-only (uname -s = $(uname -s))"
fi

RAW_ARCH=$(uname -m)
case "$RAW_ARCH" in
  x86_64)        TARGET="x86_64-apple-darwin"  ;;
  arm64|aarch64) TARGET="aarch64-apple-darwin" ;;
  *) fail "unsupported macOS architecture: $RAW_ARCH" ;;
esac

# ─── Pobierz tarball i wypakuj binarkę ─────────────────────────────────────
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

TARBALL="scrooge-agent-${TARGET}.tar.gz"
TAR_URL="${RELEASES_BASE}/${RELEASE_TAG}/${TARBALL}"

log "downloading ${TARBALL} from ${RELEASE_TAG}"
curl -fsSL --retry 3 "$TAR_URL" -o "$TMP/$TARBALL"

log "extracting binary"
tar -xzf "$TMP/$TARBALL" -C "$TMP"
[[ -f "$TMP/scrooge-agent" ]] || fail "tarball $TARBALL does not contain scrooge-agent"

# ─── Zatrzymaj poprzedni demon (idempotent re-install) ─────────────────────
if launchctl print "system/${SERVICE_LABEL}" >/dev/null 2>&1; then
  log "stopping existing scrooge-agent service"
  launchctl bootout "system/${SERVICE_LABEL}" 2>/dev/null || true
fi

# ─── Zainstaluj binarkę + utwórz katalogi ──────────────────────────────────
log "installing binary to ${BIN_DIR}/scrooge-agent"
install -d -m 755 "$BIN_DIR" "$ETC_DIR" "$DATA_DIR" "$LOG_DIR"
install -m 755 -o root -g wheel "$TMP/scrooge-agent" "${BIN_DIR}/scrooge-agent"

# ─── Zapisz CA + agent.yaml ────────────────────────────────────────────────
log "writing ${ETC_DIR}/ca.pem"
printf '%s\n' "$CA_PEM" >"${ETC_DIR}/ca.pem"
chmod 644 "${ETC_DIR}/ca.pem"

log "writing ${ETC_DIR}/agent.yaml"
cat >"${ETC_DIR}/agent.yaml" <<__SCROOGE_AGENT_YAML_EOF__
# Generated by ScroogeDLP installer ($(date -u +%Y-%m-%dT%H:%M:%SZ))
manager:
  endpoint:         "${MANAGER_ENDPOINT}"
  enrollment_token: "${ENROLLMENT_TOKEN}"
  verify_tls:       true
  ca_cert_path:     "${ETC_DIR}/ca.pem"

agent:
  data_dir:                "${DATA_DIR}"
  log_level:               "info"
  heartbeat_interval_secs: 30
__SCROOGE_AGENT_YAML_EOF__
chmod 600 "${ETC_DIR}/agent.yaml"

# ─── launchd plist ─────────────────────────────────────────────────────────
log "writing ${PLIST_PATH}"
cat >"$PLIST_PATH" <<__SCROOGE_PLIST_EOF__
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>            <string>${SERVICE_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${BIN_DIR}/scrooge-agent</string>
    <string>--config</string>
    <string>${ETC_DIR}/agent.yaml</string>
  </array>
  <key>RunAtLoad</key>        <true/>
  <key>KeepAlive</key>        <true/>
  <key>StandardOutPath</key>  <string>${LOG_DIR}/scrooge-agent.log</string>
  <key>StandardErrorPath</key><string>${LOG_DIR}/scrooge-agent.err</string>
  <key>ThrottleInterval</key> <integer>10</integer>
</dict>
</plist>
__SCROOGE_PLIST_EOF__
chown root:wheel "$PLIST_PATH"
chmod 644 "$PLIST_PATH"

# ─── Załaduj i wystartuj ───────────────────────────────────────────────────
log "loading launchd unit"
launchctl bootstrap system "$PLIST_PATH"
launchctl enable "system/${SERVICE_LABEL}" 2>/dev/null || true
launchctl kickstart -k "system/${SERVICE_LABEL}" 2>/dev/null || true

log "agent installed — connecting to ${MANAGER_ENDPOINT}"
log "tail logs:  tail -f ${LOG_DIR}/scrooge-agent.log"
log "stop:       sudo launchctl bootout system/${SERVICE_LABEL}"
