# SPDX-License-Identifier: GPL-2.0-only
# ScroogeDLP - agent installer (Windows, PowerShell curl-flow, NO code signing).
# Generated server-side by GET /api/v1/install.ps1 — do NOT edit on disk;
# the manager re-renders this every request.
#
# Windows SmartScreen / Mark-of-the-Web ustawia sie wylacznie na pliki
# pobrane przez przegladarke / Explorer. Plik pobrany przez `Invoke-WebRequest`
# i wykonany przez `Invoke-Expression` nie ma MotW, wiec niepodpisana binarka
# zarejestrowana przez `New-Service` startuje bez ostrzezen.

#Requires -RunAsAdministrator
#Requires -Version 5.1

$ErrorActionPreference = 'Stop'

# ─── Wartości wstrzyknięte przez managera ───────────────────────────────────
$ManagerEndpoint  = '{{MANAGER_ENDPOINT}}'
$InstallBaseUrl   = '{{INSTALL_BASE_URL}}'
$EnrollmentToken  = '{{ENROLLMENT_TOKEN}}'
$ReleaseTag       = '{{RELEASE_TAG}}'
$PackageVersion   = '{{PACKAGE_VERSION}}'
$ReleasesBase     = '{{RELEASES_BASE}}'

# ─── Inline CA PEM (heredoc-style here-string) ─────────────────────────────
$CaPem = @'
{{CA_PEM}}
'@

# ─── Stałe ścieżki Windows ─────────────────────────────────────────────────
$InstallDir    = 'C:\Program Files\ScroogeDLP'
$DataDir       = 'C:\ProgramData\ScroogeDLP'
$LogDir        = Join-Path $DataDir 'logs'
$AgentExePath  = Join-Path $InstallDir 'scrooge-agent.exe'
$ConfigPath    = Join-Path $DataDir 'agent.yaml'
$CaCertPath    = Join-Path $DataDir 'ca.pem'
$AgentDataDir  = Join-Path $DataDir 'agent-data'
$ServiceName   = 'ScroogeAgent'

function Write-Step($msg)  { Write-Host "▸ $msg" -ForegroundColor Cyan }
function Write-Done($msg)  { Write-Host "✓ $msg" -ForegroundColor Green }
function Write-Fail($msg)  { Write-Host "✗ $msg" -ForegroundColor Red; exit 1 }

# ─── Detekcja architektury ─────────────────────────────────────────────────
if (-not [Environment]::Is64BitOperatingSystem) {
    Write-Fail "ScroogeDLP wspiera tylko 64-bit Windows."
}
$Target = 'x86_64-pc-windows-msvc'   # ARM64 Windows: TODO gdy bedzie w releasie

# ─── Pobierz zip i wypakuj binarkę ──────────────────────────────────────────
$TmpDir   = New-Item -ItemType Directory -Path (Join-Path $env:TEMP "scrooge-install-$([guid]::NewGuid())")
$ZipName  = "scrooge-agent-$Target.zip"
$ZipUrl   = "$ReleasesBase/$ReleaseTag/$ZipName"
$ZipPath  = Join-Path $TmpDir $ZipName

try {
    Write-Step "downloading $ZipName from $ReleaseTag"
    Invoke-WebRequest -UseBasicParsing -Uri $ZipUrl -OutFile $ZipPath

    Write-Step "extracting binary"
    Expand-Archive -Path $ZipPath -DestinationPath $TmpDir -Force
    $extractedExe = Get-ChildItem -Path $TmpDir -Filter 'scrooge-agent.exe' -Recurse | Select-Object -First 1
    if (-not $extractedExe) { Write-Fail "zip $ZipName nie zawiera scrooge-agent.exe" }

    # ─── Zatrzymaj istniejacy service (idempotent re-install) ──────────────
    $existing = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
    if ($existing) {
        Write-Step "stopping existing service '$ServiceName'"
        if ($existing.Status -eq 'Running') { Stop-Service -Name $ServiceName -Force }
        # sc.exe delete poczeka az service faktycznie zniknie
        & sc.exe delete $ServiceName | Out-Null
        Start-Sleep -Seconds 2
    }

    # ─── Zainstaluj binarkę + utworz katalogi ──────────────────────────────
    Write-Step "installing binary to $AgentExePath"
    New-Item -ItemType Directory -Force -Path $InstallDir, $DataDir, $LogDir, $AgentDataDir | Out-Null
    Copy-Item -Path $extractedExe.FullName -Destination $AgentExePath -Force

    # ─── Zapisz CA + agent.yaml ────────────────────────────────────────────
    Write-Step "writing $CaCertPath"
    # Out-File domyslnie pisze UTF8 z BOM od PowerShell 6+, ale PS 5.1 daje
    # UTF8-with-BOM. Uzywamy WriteAllText z UTF8Encoding(false) bez BOM —
    # PEM parser w Rust (rcgen/rustls) jest tolerancyjny, ale lepiej clean.
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($CaCertPath, $CaPem, $utf8NoBom)

    Write-Step "writing $ConfigPath"
    $now = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
    $yamlDataDir = $AgentDataDir.Replace('\', '/')
    $yamlCaPath  = $CaCertPath.Replace('\', '/')
    $agentYaml = @"
# Generated by ScroogeDLP installer ($now)
manager:
  endpoint:         "$ManagerEndpoint"
  enrollment_token: "$EnrollmentToken"
  verify_tls:       true
  ca_cert_path:     "$yamlCaPath"

agent:
  data_dir:                "$yamlDataDir"
  log_level:               "info"
  heartbeat_interval_secs: 30
"@
    [System.IO.File]::WriteAllText($ConfigPath, $agentYaml, $utf8NoBom)

    # ─── Zarejestruj service ───────────────────────────────────────────────
    Write-Step "registering Windows service '$ServiceName'"
    # BinaryPathName musi miec poprawnie cytowanie sciezki z spacjami i flag
    $binaryPath = '"' + $AgentExePath + '" --config "' + $ConfigPath + '"'
    New-Service `
        -Name        $ServiceName `
        -BinaryPathName $binaryPath `
        -DisplayName 'ScroogeDLP Agent' `
        -Description 'ScroogeDLP endpoint agent — Data Loss Prevention monitoring and policy enforcement.' `
        -StartupType Automatic | Out-Null

    # Restart-on-failure: reset 86400s, restart po 60s przy kazdym z 3 fail'ow.
    & sc.exe failure $ServiceName reset= 86400 actions= restart/60000/restart/60000/restart/60000 | Out-Null

    Write-Step "starting service"
    Start-Service -Name $ServiceName

    Write-Done "agent installed — connecting to $ManagerEndpoint"
    Write-Host ""
    Write-Host "  status:   Get-Service $ServiceName"
    Write-Host "  logs:     Get-EventLog -LogName Application -Source '$ServiceName' -Newest 50"
    Write-Host "  stop:     Stop-Service $ServiceName"
} finally {
    if (Test-Path $TmpDir) { Remove-Item -Path $TmpDir -Recurse -Force -ErrorAction SilentlyContinue }
}
